services:
  - type: web
    name: martinsdirect-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_EMAIL
        value: wjm@martinsdirect.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Wjm
      - key: ADMIN_ROLE
        value: admin
