"""create users table

Revision ID: 538f02adb4c2
Revises: 
Create Date: 2026-03-15 15:10:44.491243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538f02adb4c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('franchises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchise_name', sa.String(length=255), nullable=False),
    sa.Column('ta_name', sa.String(length=255), nullable=True),
    sa.Column('franchise_code', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('franchise_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.Integer(), nullable=False),
    sa.Column('employee_type', sa.String(length=50), nullable=False),
    sa.Column('security_role', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('login_username', sa.String(length=100), nullable=True),
    sa.Column('login_password_hash', sa.String(length=255), nullable=True),
    sa.Column('date_employed', sa.Date(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('vendors_id', sa.String(length=100), nullable=True),
    sa.Column('pin_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_table('users')
    op.drop_table('franchises')
    # ### end Alembic commands ###
